#config.yaml

DATASET:
    base_path: '<Directory where the files mentioned below are placed>'
    train: 'SH_Train.txt'
    valid: 'SH_Val.txt'
    benchmark: 'ScutHead'
    mean_std: [[117, 110, 105], [67.10, 65.45, 66.23]]
    min_size: 600
    max_size: 1100

TRAINING:
    exp_name: 'ScutHead_R50'
    backbone : 'resnet50'
    only_backbone : False
    pretrained_model:
    save_dir: '<Directory to save the model?>'
    start_epoch: 1
    eval_every: 10
    log_dir: './Logs/'
    milestones: [10, 20, 25]
    max_epoch: 30

HYPER_PARAM:
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    gamma: 0.1
    batch_size: 2

NETWORK:
    use_deform: False
    ohem: True
    context: 'cpm'
    custom_sampling: False
    soft_nms: False
    upscale_rpn: True
    median_anchors: True
