version: '2.3'

services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    env_file:
      - "docker-compose-env/main.env"
    volumes:
      # - ./data/:/data
      - /media/mmlab/hdd/:/data
    ports:
      # - "27234:8097"
      - "10050:22"
    stdin_open: true
    tty: true
    # volumes:
    # - "./dataset:/dataset"

